"use client"

import { useMemo } from "react"
import { ChevronDown, ChevronRight } from "lucide-react"
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  flexRender,
  type ColumnDef,
} from "@tanstack/react-table"
import { cn } from "@/lib/utils"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Skeleton } from "@/components/ui/skeleton"
import { useDataGrid } from "./hooks/use-data-grid"
import { DataGridHeaderCell } from "./data-grid-header"
import { DataGridPagination } from "./data-grid-pagination"
import { getNestedValue, formatCellValue, getAlignmentClass, getColumnWidthStyle, isGroupRow } from "./utils"
import type { ColumnConfig, GroupedRow } from "./types"

export function DataGridTable<TData>() {
  const { 
    config, 
    state, 
    actions, 
    processedData, 
    totalCount,
    flattenedGroupedData,
    metadata,
  } = useDataGrid<TData>()
  
  const features = {
    sorting: true,
    filtering: true,
    pagination: true,
    ...config.features,
  }

  const pivotColumnMeta = useMemo(() => (
    Array.isArray(metadata?.pivotColumns)
      ? metadata.pivotColumns as Array<{ id: string; valueId: string; header?: string; labels: string[] }>
      : []
  ), [metadata])

  const pivotColumnMap = useMemo(
    () => new Map(pivotColumnMeta.map((item) => [item.id, item])),
    [pivotColumnMeta]
  )
  
  // Transform column config to TanStack Table column defs
  // respect ordering stored in state.columnOrder (provided by DataGridProvider)
  // and omit any pivot columns when server has generated pivotResultCols
  const columns: ColumnDef<TData>[] = useMemo(() => {
    const pivotCols = state.pivotState.columnGroups.map(cg => cg.id)
    const pivotModeActive = pivotCols.length > 0
    const orderMap = new Map(state.columnOrder.map((id, idx) => [id, idx]))
    const baseCols = [...config.columns]
      .filter((c) => {
        if (pivotCols.includes(c.id)) {
          return false
        }
        if (!pivotModeActive) {
          return true
        }
        return state.pivotState.rowGroups.some((group) => group.id === c.id)
      })
      .sort((a, b) => {
        const ai = orderMap.has(a.id) ? orderMap.get(a.id)! : Infinity
        const bi = orderMap.has(b.id) ? orderMap.get(b.id)! : Infinity
        return ai - bi
      })

    // build ColumnDefs for the base columns first
    const defs: ColumnDef<TData>[] = baseCols.map((col): ColumnDef<TData> => ({
      id: col.id,
      accessorFn: col.accessorFn || (col.accessorKey 
        ? (row) => getNestedValue(row, col.accessorKey!)
        : undefined
      ),
      header: ({ column }) => {
        const sortDirection = column.getIsSorted()
        const isFiltered = column.getIsFiltered()
        const filterValue = column.getFilterValue()
        
        if (col.headerCell) {
          return col.headerCell()
        }
        
        return (
          <DataGridHeaderCell
            column={col}
            sortDirection={sortDirection}
            isFiltered={isFiltered}
            onSort={() => {
              if (col.enableSorting !== false) {
                column.toggleSorting()
              }
            }}
            onFilter={(value) => {
              column.setFilterValue(value)
            }}
            onClearFilter={() => {
              column.setFilterValue(undefined)
            }}
            currentFilterValue={filterValue}
          />
        )
      },
      cell: ({ getValue, row, cell }) => {
        const value = getValue()
        
        if (col.cell) {
          return col.cell(value, row.original, row.index)
        }
        
        const formatted = formatCellValue(value, col)
        
        return (
          <div 
            className={cn(
              "px-3 py-2",
              getAlignmentClass(col.align),
              col.className
            )}
          >
            {formatted}
          </div>
        )
      },
      enableSorting: col.enableSorting !== false && features.sorting,
      enableColumnFilter: col.enableFiltering !== false && features.filtering,
      enableHiding: col.enableHiding !== false,
      size: typeof col.width === "number" ? col.width : undefined,
      minSize: col.minWidth,
      maxSize: col.maxWidth,
    }))

    // append any dynamic pivot columns generated by SSRM
    if (pivotColumnMeta.length === 0) {
      return defs
    }

    const buildPivotLeaf = (pivotMeta: { id: string; valueId: string; header?: string; labels: string[] }): ColumnDef<TData> => {
      const valueColumn = config.columns.find((column) => column.id === pivotMeta.valueId)
      return {
        id: pivotMeta.id,
        accessorFn: (row: unknown) => (row as Record<string, unknown>)[pivotMeta.id],
        header: valueColumn?.header || pivotMeta.header || pivotMeta.valueId,
        cell: ({ getValue }) => {
          const value = getValue()
          return (
            <div
              className={cn(
                "px-3 py-2",
                getAlignmentClass(valueColumn?.align),
                valueColumn?.className
              )}
            >
              {valueColumn ? formatCellValue(value, valueColumn) : String(value ?? "-")}
            </div>
          )
        },
        enableSorting: false,
        enableFiltering: false,
        size: typeof valueColumn?.width === "number" ? valueColumn.width : undefined,
        minSize: valueColumn?.minWidth,
        maxSize: valueColumn?.maxWidth,
      }
    }

    const pivotRoots: Array<ColumnDef<TData>> = []
    const pivotGroupIndex = new Map<string, ColumnDef<TData> & { columns: ColumnDef<TData>[] }>()

    for (const pivotMeta of pivotColumnMeta) {
      let currentPath = ""
      let siblingGroups = pivotRoots

      pivotMeta.labels.forEach((label, index) => {
        currentPath = currentPath ? `${currentPath}::${label}` : label
        const existing = pivotGroupIndex.get(currentPath)
        if (existing) {
          siblingGroups = existing.columns
          return
        }

        const group: ColumnDef<TData> & { columns: ColumnDef<TData>[] } = {
          id: `pivot-group-${currentPath}`,
          header: label,
          columns: [],
        }
        siblingGroups.push(group)
        pivotGroupIndex.set(currentPath, group)
        siblingGroups = group.columns
      })

      siblingGroups.push(buildPivotLeaf(pivotMeta))
    }

    return [...defs, ...pivotRoots]
  }, [config.columns, features.sorting, features.filtering, pivotColumnMeta, state.columnOrder, state.pivotState.columnGroups, state.pivotState.rowGroups])
  
  // Create table instance
  const table = useReactTable({
    data: processedData,
    columns,
    state: {
      sorting: state.sorting,
      columnFilters: state.columnFilters,
      columnVisibility: state.columnVisibility,
      rowSelection: state.rowSelection,
      globalFilter: state.globalFilter,
      pagination: {
        pageIndex: state.pageIndex,
        pageSize: state.pageSize,
      },
    },
    onSortingChange: actions.setSorting,
    onColumnFiltersChange: actions.setColumnFilters,
    onColumnVisibilityChange: actions.setColumnVisibility,
    onRowSelectionChange: actions.setRowSelection,
    onGlobalFilterChange: actions.setGlobalFilter,
    onPaginationChange: (updater) => {
      const newPagination = typeof updater === "function"
        ? updater({ pageIndex: state.pageIndex, pageSize: state.pageSize })
        : updater
      actions.setPageIndex(newPagination.pageIndex)
      actions.setPageSize(newPagination.pageSize)
    },
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: config.dataSource.type === "client" ? getSortedRowModel() : undefined,
    getFilteredRowModel: config.dataSource.type === "client" ? getFilteredRowModel() : undefined,
    getPaginationRowModel: config.dataSource.type === "client" ? getPaginationRowModel() : undefined,
    manualPagination: config.dataSource.type === "server",
    manualSorting: config.dataSource.type === "server",
    manualFiltering: config.dataSource.type === "server",
    pageCount: Math.ceil(totalCount / state.pageSize),
    getRowId: config.getRowId,
  })
  
  const rows = table.getRowModel().rows
  const visibleColumns = table.getVisibleLeafColumns()
  const hasGroupedRows = flattenedGroupedData.length > 0

  const renderLeafCell = (columnId: string, row: TData, index: number) => {
    const column = config.columns.find((item) => item.id === columnId)
    if (!column) {
      return null
    }

    const value = column.accessorFn
      ? column.accessorFn(row)
      : column.accessorKey
        ? getNestedValue(row, column.accessorKey)
        : undefined

    if (column.cell) {
      return column.cell(value, row, index)
    }

    return (
      <div
        className={cn(
          "px-3 py-2",
          getAlignmentClass(column.align),
          column.className
        )}
      >
        {formatCellValue(value, column)}
      </div>
    )
  }

  const renderGroupCell = (
    columnId: string,
    groupRow: GroupedRow<TData>,
    depth: number,
    pathKey: string
  ) => {
    const column = config.columns.find((item) => item.id === columnId)
    const pivotMeta = pivotColumnMap.get(columnId)
    const valueColumn = pivotMeta
      ? config.columns.find((item) => item.id === pivotMeta.valueId)
      : undefined
    const renderColumn = column || valueColumn

    if (!renderColumn && !pivotMeta) {
      return <div className="min-h-10 px-3 py-2" />
    }

    const isGroupingColumn = column?.id === groupRow.groupField
    const aggregationValue = groupRow.aggregations?.[columnId]

    if (isGroupingColumn) {
      const isExpanded = state.expandedGroups.has(pathKey)
      return (
        <button
          type="button"
          onClick={() => actions.toggleGroup(pathKey)}
          className="flex min-h-10 w-full items-center gap-2 px-3 py-2 text-left"
          style={{ paddingLeft: `${depth * 20 + 12}px` }}
        >
          {isExpanded ? <ChevronDown className="size-4 shrink-0" /> : <ChevronRight className="size-4 shrink-0" />}
          <span className="font-medium">{groupRow.groupValue}</span>
          <span className="text-xs text-muted-foreground">({groupRow.childCount})</span>
        </button>
      )
    }

    if (aggregationValue !== undefined) {
      return (
        <div
          className={cn(
            "px-3 py-2 font-medium",
            getAlignmentClass(renderColumn?.align),
            renderColumn?.className
          )}
        >
          {renderColumn ? formatCellValue(aggregationValue, renderColumn) : String(aggregationValue)}
        </div>
      )
    }

    return <div className="min-h-10 px-3 py-2" />
  }
  
  return (
    <div className="space-y-4">
      {/* Table */}
      <div className="rounded-md border overflow-x-auto">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  const colConfig = config.columns.find(c => c.id === header.column.id)
                  
                  return (
                    <TableHead
                      key={header.id}
                      style={colConfig ? getColumnWidthStyle(colConfig) : undefined}
                      className="p-0"
                    >
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHead>
                  )
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {state.isLoading ? (
              // Loading skeleton
              Array.from({ length: state.pageSize }).map((_, i) => (
                <TableRow key={`skeleton-${i}`}>
                  {config.columns.map((col) => (
                    <TableCell key={col.id} className="p-3">
                      <Skeleton className="h-5 w-full bg-muted/35" />
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : hasGroupedRows ? (
              flattenedGroupedData.map((item, index) => {
                const pathKey = item.path.join("::")

                if (isGroupRow(item.data)) {
                  return (
                    <TableRow key={`group-${pathKey}`} className="bg-muted/30 hover:bg-muted/40">
                      {visibleColumns.map((column) => (
                        <TableCell key={`${pathKey}-${column.id}`} className="p-0 align-middle">
                          {renderGroupCell(column.id, item.data, item.depth, pathKey)}
                        </TableCell>
                      ))}
                    </TableRow>
                  )
                }

                return (
                  <TableRow key={`row-${pathKey}-${index}`}>
                    {visibleColumns.map((column) => (
                      <TableCell key={`${pathKey}-${column.id}`} className="p-0">
                        {renderLeafCell(column.id, item.data, index)}
                      </TableCell>
                    ))}
                  </TableRow>
                )
              })
            ) : rows.length === 0 ? (
              // Empty state
              <TableRow>
                <TableCell
                  colSpan={columns.length}
                  className="h-24 text-center text-muted-foreground"
                >
                  No results found
                </TableCell>
              </TableRow>
            ) : (
              // Data rows
              rows.map((row) => (
                <TableRow
                  key={row.id}
                  data-state={row.getIsSelected() && "selected"}
                >
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id} className="p-0">
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
      
      {/* Pagination */}
      {features.pagination && (
        <DataGridPagination
          pageIndex={state.pageIndex}
          pageSize={state.pageSize}
          totalRows={totalCount}
          pageSizeOptions={config.pagination?.pageSizeOptions || [10, 20, 50, 100]}
          onPageChange={actions.setPageIndex}
          onPageSizeChange={actions.setPageSize}
          showPageSizeSelector={config.pagination?.showPageSizeSelector !== false}
          showRowCount={config.pagination?.showRowCount !== false}
          isLoading={state.isLoading}
        />
      )}
      
      {/* Error display */}
      {state.error && (
        <div className="rounded-md bg-destructive/10 p-4 text-destructive text-sm">
          Error loading data: {state.error.message}
        </div>
      )}
    </div>
  )
}
